version: '3.8'

services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000
      SPRING_APPLICATION_NAME: Gateway
      EUREKA_INSTANCE_HOSTNAME: host.docker.internal
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8100/eureka
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_PROVIDER: my-provider
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-ID: GW2
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-SECRET: GW2Secret
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_SCOPE: openid
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_REDIRECT-URI: http://localhost:8000/login/oauth2/code/gateway
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_ISSUER-URI: http://host.docker.internal:8200
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_AUTHORIZATION-URI: http://localhost:8200/oauth2/authorize
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_TOKEN-URI: http://host.docker.internal:8200/oauth2/token