version: '3.8'

services:
  gateway:
    image: stargazingsparrow/gateway:latest
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_APPLICATION_NAME: Gateway
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: ${EUREKA}
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_PROVIDER: my-provider
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-ID: ${OAUTH2_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-SECRET: ${OAUTH2_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_SCOPE: openid
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_REDIRECT-URI: ${OAUTH2_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_ISSUER-URI: ${OAUTH2_ISSUER_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_AUTHORIZATION-URI: ${OAUTH2_AUTH_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_TOKEN-URI: ${OAUTH2_TOKEN_URI}
      JAVA_OPTS: "-Xms256m -Xmx1024m"
    networks:
      - app-network

networks:
  app-network:
    external: true