management:
  health:
    redis:
      enabled: ${MANAGEMENT_HEALTH_REDIS_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        auto-time-requests: true
        request:
          autotime:
            enabled: true
    observations:
      annotations:
        enabled: true


spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Gateway}
  main:
    web-application-type: ${SPRING_MAIN_WEB-APPLICATION-TYPE:reactive}
    allow-bean-definition-overriding: ${SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING:true}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      metrics:
        enabled: true
      routes:
        # USER SERVICE
        - id: auth-signup-password
          predicates:
            - Path=/v1/auth/**
            - Method=POST
          uri: ${USERSERVICE_URI:lb://userservice}

        - id: roles-get
          predicates:
            - Path=/v1/roles/**
            - Method=GET
          uri: ${USERSERVICE_URI:lb://userservice}
          filters:
            - TokenRelay=
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        - id: roles-post
          predicates:
            - Path=/v1/roles/**
            - Method=POST
          uri: ${USERSERVICE_URI:lb://userservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        - id: user-get
          predicates:
            - Path=/v1/users/**
            - Method=GET
          uri: ${USERSERVICE_URI:lb://userservice}
          filters:
            - TokenRelay=
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        - id: user-roles-post
          predicates:
            - Path=/v1/users/**
            - Method=POST
          uri: ${USERSERVICE_URI:lb://userservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        # PRODUCT SERVICE
        - id: productservice-get
          predicates:
            - Path=/v1/products/**
            - Method=GET
          uri: ${PRODUCTSERVICE_URI:lb://productservice}
          filters:
            - TokenRelay=
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10000
                redis-rate-limiter.burstCapacity: 30000

        - id: productservice-post-patch-delete
          predicates:
            - Path=/v1/products/**
            - Method=POST,PATCH,DELETE
          uri: ${PRODUCTSERVICE_URI:lb://productservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 5000

        # CART SERVICE
        - id: cartservice-get
          predicates:
            - Path=/v1/cart/**
            - Method=GET
          uri: ${CARTSERVICE_URI:lb://cartservice}
          filters:
            - TokenRelay=
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 5000

        - id: cartservice-post-patch-delete
          predicates:
            - Path=/v1/cart/**
            - Method=POST,PATCH,DELETE
          uri: ${CARTSERVICE_URI:lb://cartservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 5000

        # ORDER SERVICE
        - id: orderservice-get
          predicates:
            - Path=/v1/orders/**
            - Method=GET
          uri: ${ORDERSERVICE_URI:lb://orderservice}
          filters:
            - TokenRelay=
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        - id: orderservice-post-patch
          predicates:
            - Path=/v1/orders/**
            - Method=POST,PATCH
          uri: ${ORDERSERVICE_URI:lb://orderservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        # PAYMENT SERVICE
        - id: paymentservice-post
          predicates:
            - Path=/v1/payments
            - Method=POST
          uri: ${PAYMENTSERVICE_URI:lb://paymentservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        - id: paymentservice-webhooks
          predicates:
            - Path=/v1/payments/webhooks
            - Method=POST
          uri: ${PAYMENTSERVICE_URI:lb://paymentservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        # NOTIFICATION SERVICE
        - id: notificationservice-post
          predicates:
            - Path=/v1/notifications/send-message
            - Method=POST
          uri: ${NOTIFICATIONSERVICE_URI:lb://notificationservice}
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_PROVIDER:my-provider}
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-ID:GW2}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-SECRET:GW2Secret}
            authorization-grant-type: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_AUTHORIZATION-GRANT-TYPE:authorization_code}
            scope:
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_SCOPE:openid}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_REDIRECT-URI:http://localhost:8000/login/oauth2/code/gateway}
        provider:
          my-provider:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_ISSUER-URI:http://localhost:8200}
            authorization-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_AUTHORIZATION-URI:http://localhost:8200/oauth2/authorize}
            token-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_TOKEN-URI:http://localhost:8200/oauth2/token}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8000}

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER-WITH-EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH-REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://localhost:8100/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instanceId: ${EUREKA_INSTANCE_HOSTNAME:localhost}:${SERVER_PORT:8000}
    preferIpAddress: false

logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_RATELIMIT:DEBUG}
    org.springframework.data.redis: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS:DEBUG}