# ════════════════════════════════════════════════════════════════
# NOTIFICATION SERVICE
# (no DB — Kafka only)
# ════════════════════════════════════════════════════════════════
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: notificationservice
          image: stargazingsparrow/notificationservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8700
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SERVER_PORT
              value: "8700"
            - name: EUREKA_CLIENT_REGISTER-WITH-EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH-REGISTRY
              value: "false"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "10.0.0.2:9092"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://62.238.15.118:30200"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://62.238.15.118:30200/oauth2/jwks"
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  selector:
    app: notificationservice
  ports:
    - port: 8700
      targetPort: 8700
      nodePort: 30700
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notificationservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationservice
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
