version: '3.8'

services:
  productservice:
    image: stargazingsparrow/productservice:latest
    container_name: productservice
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      RESOURCE_SERVER: ${RESOURCE_SERVER}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK: ${JWK_URI}
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: ${EUREKA}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
      SPRING_ELASTICSEARCH_URIS: ${ELASTIC_SEARCH_URI}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
    networks:
      - app-network

networks:
  app-network:
    external: true